---
title: "Ken Griffey Jr. Career Statistics"
author: "Alex Greb"
date: 11/18/24
output: 
  flexdashboard::flex_dashboard:
    orientation: columns # can be rows or columns
    vertical_layout: fill # can be scroll or fill
    source_code: embed
    theme:
      bootswatch: lux
    navbar: 
      - { title: "Alex Greb", href: "https://agreb21.github.io", align: right }
      - { icon: "fa fa-github", href: "https://github.com/AGreb21", align: right, target: blank }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(here)
library(janitor)
library(ggthemes)
library(kableExtra)
```

```{r}
griffeydata <- read_csv(here("data/KenGriffyJr.csv"))
griffeydata <- griffeydata %>%
  clean_names()
```

```{r}
griffeydata <- griffeydata[-c(21,22), ]
griffeydata <- griffeydata %>%
  mutate(tm = ifelse(tm == "TOT", "CIN", tm)) %>%
  mutate(lg = ifelse(lg == "MLB", "NL", lg))
```



Column {data-width=350}
-----------------------------------------------------------------------

### Griffey Homeruns By Team

```{r}
homerun_graph <- ggplot(griffeydata, aes(x = tm, y = hr, color = tm)) +
  geom_boxplot() +
  theme_solarized()+
  labs(
    #title = "Griffey Homeruns by Team",
    x = "Team",
    y = "Homeruns"
  )

ggplotly(homerun_graph)
```

### Griffey data 

```{r}
#starwars <- starwars %>%
 # select(name, height, mass, gender, species, homeworld)

knitr::kable(griffeydata) #%>%
  #kableExtra::kable_styling(bootstrap_options = c("striped", "hover"), full_width = F) %>%
  #kableExtra::scroll_box(width = "30%", height = "300px") %>%
  #kableExtra::kable_styling(font_size = 10)
```


Column {data-width=350}
-----------------------------------------------------------------------

### Griffey OPS+ By Season

```{r}
ops_plus_graph <- ggplot(griffeydata, aes(x = year, y = ops_2, color = tm)) +
  geom_point() +
  labs(
    #title = "Griffey OPS+ by season",
    x = "Year",
    y = "OPS +",
    color = "Team"
  ) +
  theme_solarized()+
  geom_smooth(color = "black")

ggplotly(ops_plus_graph)
```


### Griffey Batting Average By Year
```{r}
batting_average_graph <- ggplot(griffeydata, aes(x = year, y = ba)) +
  geom_line()+
  labs(
    #title = "Griffey Batting Average by Year",
    x = "Year",
    y = "Batting Average"
  )+
  theme_solarized()

ggplotly(batting_average_graph)
```


### Ken Griffey Jr.'s Career Overview
The data I am using for my dashboard is the career statistics of Ken Griffey Jr.  I wanted to explore how he got better or worse over his career, as well as the differences in his statistics for the different teams he played on.

Data author: Jarred Priester
https://www.kaggle.com/datasets/jarredpriester/ken-griffey-jr-career-stats











